### ISSUE TITLE
When deleting a component, allow user to delete spreadsheet too

### ISSUE THREAD

**Issue by riverole** [paperize/paperize#11]
**Is your feature request related to a problem? Please describe.**
When deleting a component from Paperize, you might end up with orphan spreadsheets that were created by Paperize (by checking the checkbox).

**Describe the solution you'd like**
A checkbox when deleting a component that allows to delete the associated spreadsheet (if there was any).

**Describe alternatives you've considered**
Manually deleting the spreadsheet.

**Comment by lorennorman** [comment]
This one is a no-go for a few of reasons:
- multiple components may rely on same sheet
- worksheet vs spreadsheet: components use only one worksheet out of a spreadsheet, is it ever appropriate to clean up the whole sheet?
- I don't want to ever implement any code that deletes things in a user's drive (accidents can't happen if we never write the code in the first place)
- I want to shift down to `drive.file` access, and I don't know if that will let us delete things anyway

I am however open to doing some signaling, maybe a mention that says "this sheet is no longer used, you may delete it if you like!" with a link to Drive to make it easy.

Closing for now, but still open to discussion!
