### ISSUE TITLE
En dash is not read from spreadsheet cells

### ISSUE THREAD

**Issue by Itangalo** [paperize/paperize#114]
**Describe the bug**
En dashes (–) seem to be left out when Paperize reads text from Google spreadsheet. This makes it problematic to write intervals correctly, such as 3–18.

**To Reproduce**
1. Write "3–1" in a cell in a sheet used by Paperize.
2. Create a text layer, use the relevant column to import text.
3. Preview the relevant component.
4. The text is displayed as "3 10".

**Expected behavior**
I expect the dash to show.

**Screenshots**
<img width="167" alt="image" src="https://user-images.githubusercontent.com/262940/154232396-03b56e88-9098-4f05-b342-ac41a5a44591.png">

**Additional context**
I'm using the standard Helvetica font, so it doesn't seem to be an issue with missing characters in the font. (Have also tried Times New Roman.) I assume the same thing happens with some other non-standard characters, but for example åäö (used in Sweden) works fine.

**Comment by Itangalo** [comment]
Investigating the text further, I can see that it is _not_ a standard blank space between 3 and 10.

**Comment by lorennorman** [comment]
Interesting one. A few things:
- the lowercase fonts at the top of the font list are built-in to PDF, and they usually have _fewer_ glyphs than the full set
  - helvetica and times are both from this truncated font set
- try a google font (capitalized ones in the font dropdown) and see what happens?
- try pasting the glyph into a text layer directly? (makes sure we aren't losing it in transit from Google Sheets)

**Comment by Itangalo** [comment]
Two points to you. I tried one of the uppercase fonts, and the dash appears. So it was a font issue after all.

I'll keep this in mind and add something to the documentation. I would probably vote for removing the truncated font sets, but that's another matter. Feel free to close this issue!

**Comment by Itangalo** [comment]
Side note: I actually considered writing "times" instead of "Times New Roman", and "helvetica" instead of "Helvetica", but went for the style I thought felt best. I should be more true to the actual settings when I report bugs. :-)

**Comment by lorennorman** [comment]
All good, thanks for the report and fix!
