### ISSUE TITLE
Drag and drop for reordering layers shows entire list of layers

### ISSUE THREAD

**Issue by Itangalo** [paperize/paperize#140]
**Describe the bug**
When dragging to reorder layers in the component editor, not only the selected layer is dragged around but the entire list of layers. (It works as expected, but is visually confusing.)

**To Reproduce**
1. Open a component editor.
2. Create two layers.
3. Click and drag on the second layer.

**Expected behavior**
Only the row for the selected layer should (visually) be dragged around.

**Screenshots**
<img width="758" alt="image" src="https://user-images.githubusercontent.com/262940/179614933-34cea875-af1a-4702-91de-25d5368d5062.png">

**Comment by lorennorman** [comment]
Turns out this was a Chrome bug, couldn't repro under Firefox for some reason!

Fixed in the just-deployed version `8.3.1-exp`. Thank you!
