### ISSUE TITLE
Study up on jsPDF new features after 1.5.3

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#142]
Read through all of the releases of jsPDF after version `1.5.3` and make note of the important changes as comments to this Issue. "Important" is defined as:
- something that will break our usage of jsPDF
- a new feature we're likely to want to use

Here's their releases page:
https://github.com/parallax/jsPDF/releases

**Comment by DarkenPL** [comment]
Removed APIs that were previously marked as deprecated. Namely: addHTML, fromHTML, html2pdf, addSvg, addButton, addTextField, addChoiceField, cellInitialize, setFontStyle, setFontType, clip_fixed.

There is a new function, where pdf is generated from html https://rawgit.com/MrRio/jsPDF/master/docs/module-html.html#~html

PDF compression was improved on version v2.2.0

**Comment by lorennorman** [comment]
> ...compression was improved...

Excellent, might get some filesize performance out of this for free. We need to test this out on your large game exports, @DarkenPL.

Thanks for taking a look at this!
