### ISSUE TITLE
Layer Visibility

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#17]
**Describe the solution you'd like**
A checkbox in the layer settings that lets the user hide/show individual layers from being printed.

This is helpful during intense editing sessions in case a user needs a better view of another layer, or is just trying a few different options.

**Comment by riverole** [comment]
Should this checkbox be in the layer settings, or at summary of the layers level? If it is at the specific layer settings, then I guess I should indicate somehow (maybe strikethrough) the layer, to indicate that is hidden. Right?

**Comment by lorennorman** [comment]
I’m open to what feels right. Maybe it is on the summary itself, and it
uses an eyeball icon: open when visible, closed when hidden. That’s
familiar from adobe tools, maybe?

**Comment by riverole** [comment]
Sounds good, do these look good enough?
<img width="53" alt="layerEnabled" src="https://user-images.githubusercontent.com/4833422/73317301-7936ab00-41ea-11ea-9658-115eb39db239.png">
<img width="53" alt="layerDisabled" src="https://user-images.githubusercontent.com/4833422/73317294-7471f700-41ea-11ea-84fe-5abb0dec0805.png">

**Comment by lorennorman** [comment]
they do! are you using the icons that are included already? mdi icons i
think? that reminds me i need to add that to the README...
