### ISSUE TITLE
Selective Component Printing

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#18]
**Describe the solution you'd like**
A new section of the Print Settings that allows the user to select which components will be printed. This is helpful for speeding up iteration when working on a single component of a multi-component game with many items.

**Comment by riverole** [comment]
How would the UX be for this? In the print settings a radio box between print all or select components, and then that shows the list of components that then you can select specific ones (in a tags style type of UI)?

**Comment by lorennorman** [comment]
Sounds reasonable, but what is meant by "tags style"?

**Comment by riverole** [comment]
A textbox, where it autocompletes to the names of your components and when you select one it appears as selected in the select

**Comment by lorennorman** [comment]
I'm not sure! I was thinking to list all the components with checkboxes or toggle buttons next to them, but I'm open to other ideas. I believe most people's projects will have 1-3 components, so I'd like to focus on that use case. Someone with 10 will be quite rare I bet.

What do you think?

**Comment by riverole** [comment]
Checkboxes is so 2019! Xd. Just kidding. We can do checkboxes, it will definitely be easier.

**Comment by riverole** [comment]
Uhhhhhhm. It seems that the print settings are at the global level. So, I feel like they would need to be related to a specific game, if we need to select the components. Otherwise, we can still dynamically load the components for a specific game and checkboxes, etc, and then store it in the game itself, although presenting it in the print settings, which might be a bit confusing (at least from dev perspective). Does it make sense?

**Comment by lorennorman** [comment]
Dang, good point! I will have to think about that a bit more.

**Comment by lorennorman** [comment]
Taking a shot at this...

Perhaps we add a `printSettings` attribute to each game in the `games` store?

```javascript
printSettings: {
  componentIdsToPrint: []
}
```

And then we can have the array of checkboxes map to that array. I feel like I'm forgetting something. Maybe managing that array when components get added/removed is an issue? Open to thoughts.

**Comment by riverole** [comment]
Would that printSettings have all the print settings, or only the component ids?

**Comment by lorennorman** [comment]
Just the print settings that are specific to this game, meaning just the component ids.

That's an interesting question, though. Does it make sense to have specific printing settings per-game, and just do away with the global print settings?
