### ISSUE TITLE
Copying Layers

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#43]
Add a suitable "copy" icon onto the Layer list at the left of the Template Editor. Wire it up to the `copyLayer` action. Ensure that the referenced Dimension is also copied.

**Comment by riverole** [comment]
I have a couple of questions:
- So, it should create a new dimension id, that is a copy of the previous one, right? 
- After creating a layer, should it set the active layer to the new layer?
- Should the copied layer be inserted after the one that is being copied from?

**Comment by lorennorman** [comment]
New dimension with new id 
Yes set it active, unless that’s weird in the ui 
Yeah insert right after. Little reordering to do there!
