### ISSUE TITLE
Copying Components

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#45]
UI:
- In the "New Component" form there could be a "copy exisitng component" option with a list of components to copy
- When editing a component, there could be a "copy this component" button that copies this component in place

Copied components need to deep copy their templates (which deep copy their layers... this gets interesting!) but can keep shallow references to Spreadsheets and Worksheets.

**Comment by riverole** [comment]
For the first case, when we are doing a New Component, but we're selecting copying from a component, are we keeping references to the old ones as well? In that case, are we disabling the checkbox to create the spreadsheets?

**Comment by lorennorman** [comment]
Good point. Thinking...

Yeah it can just copy the spreadsheet and worksheet ids, and thus point to
the same ones. Makes sense because they are remote resources anyway.

Hide the spreadsheet checkbox on copy.
