### ISSUE TITLE
Copying Games

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#46]
UI:
- in the "New Game" form we can add a "Copy Existing Game" option with a list of other games (not present if no other games)

Deep copy each component, I guess! At this point we will have built up so much copying that it's hard to really know what pitfalls we'll hit to get here, but if we can make this work appropriately then we'll have given our users A LOT of power.

**Comment by riverole** [comment]
Hi! Kind of the same thing as per the components... Should we allow to create new folders, etc.. when copying from an existing game? I assume we should, right? Otherwise it seems a bit weird.

**Comment by riverole** [comment]
As we talked, we will put this on standby, since all the other copyings should probably bring most of the required functionality, and game copying for the moment doesn't seem to be a priority for users. We'll reevaluate later, once copying is live, and see what are the opinions from the users.
