### ISSUE TITLE
Change template vars to use triple-curlies by default

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#49]
The Mustache templating language (and by extension, tiny-mustache, which Paperize uses) automatically escapes HTML. This is undesirable for Paperize users as they are not rendering to an HTML target.

We can easily change this by using 3 curly braces to open/close template variables, and we should do so by default.

- [ ] change all built-in references to use `{{{Variable}}}` instead of `{{Variable}}`

Let's do this in both the auto-generated template, and any help text we have in the app or docs.

**Comment by shawn-mcgee** [comment]
So, I am starting to work on this. Is this just a tiny-mustache thing? because vue also uses a double curly brace notation for some variables? I'm trying to think of an easy way to clean this up, but if I must I will absolutely review every single case of double curly braces 😛 .

**Comment by lorennorman** [comment]
Yeah just tiny-mustache. I didn’t think about the confusion with vue
templates, ha!

Text layer and text renderer files are the most likely places. I’ll look at
the file structure and try to provide better nudges a little later.
