### ISSUE TITLE
When editing a Component, size doesn't show the selected or default value

### ISSUE THREAD

**Issue by riverole** [paperize/paperize#5]
**Describe the bug**
When you click to edit a component, the size has no default or selected value (whereas Orientation has, for example).

**To Reproduce**
1. Click on edit a game.
2. Click on edit a component.

**Expected behavior**
Size should have a default value show (or the selected one), probably Poker Sized Cards.

**Screenshots**
<img width="498" alt="NoDefaultOrSelectedValue" src="https://user-images.githubusercontent.com/4833422/73116166-9582d100-3ee6-11ea-8fe7-616bb0f05d08.png">

**Desktop (please complete the following information):**
- Operating System: MacOS
- Browser: Chrome
- Paperize Version: ver.A7.0.1

**Additional context**
If you select a size and save, it will show the selected value, but if you reload the page again or log out and log in again, it won't show anymore.

**Comment by riverole** [comment]
Kind of weird behavior on this editor. Basically, when you open the editor, it uses a predetermined value for the orientation and an empty value for the size. Then, if you actually change it, then it does save the template, so if you print, it will take effect the changes you made (so if you change to landscape, it will print in landscape, and it will show as landscape in the edit). However, if you refresh the page again, it would also come back to the defaults of portrait and empty size. Still, if you don't change them, the actual values that are used will be the ones stored from the template (so it would print in landscape, even though it will say portrait there). I don't think this should be the expected behavior.

**Comment by riverole** [comment]
I see! It seems that what's being stored for size is only the actual size (not the portrait, custom, etc...), which means that is impossible to reverse populate the editor with the existing values (since for example, it could be a custom size, or just reversed the values, or whatnot). Is there any reason (aside from storing less, etc...) to lose that information @lorennorman? I totally get storing the actual sizes (so you don't have to have those transformations anywhere else, so it's only the responsibility of the TemplateSizeEditor to do those transformations), but still I think it wouldn't hurt to store as well the orientation, paper size (if not custom) and the custom vs standard. Otherwise the CX is a bit weird (since people will say: but I already changed this!). I could do this, if you wanted.

**Comment by lorennorman** [comment]
Great work doing some ancient code archeology! There are no good reasons for what was done here, it just accumulated on the side without me focusing on it, and it sounds like you've found all the pitfalls.

Make a branch and take a swing at fixing it! We can chat more on the Pull Request if things end up a little hairier than you thought.

(Totally optional, but a test would also be great if you're up for playing with Cypress.)

**Comment by riverole** [comment]
Actually, when are selecting one component we are loading the numbers for all of them at the same time. Why can't we just do that once we have opened the game page? Why do we need to wait until they select a specific component?

**Comment by lorennorman** [comment]
That make sense to me, basically pre-flight the spreadsheet download upon entering the page.

Important note: each component COULD use a different spreadsheet altogether. The expectation is that they'll all use different worksheets inside of the same spreadsheet, but it is possible to reference entirely different sheets. So you really need to map components to their spreadsheet IDs then de-duplicate the collection and fetch whatever's left.

Wait a minute, I just noticed this Issue is about the dimensions, I think you were talking about #4 though? Just left the comment in the wrong place or am I missing something?

**Comment by riverole** [comment]
Wow, totally, sorry, XD.

**Comment by lorennorman** [comment]
Haha no worries!

**Comment by lorennorman** [comment]
Fixed by #20 !
