### ISSUE TITLE
If selecting a image that you just uploaded to your drive to add in a template, it won't show until you refresh the page

### ISSUE THREAD

**Issue by riverole** [paperize/paperize#6]
**Describe the bug**
If you select an image that you just uploaded to your drive images folder to add to a template, the image will not show. If you refresh the page though, it will start showing, and then any other time that you use it it will work.

**To Reproduce**
1. Go to edit a component's template.
2. In parallel, upload a new image to your drive folder.
3. Try to add a new Image layer, selecting static image and picking the image that you just uploaded to drive.

**Expected behavior**
The new image is show in the pdf render.

** Desktop (please complete the following information):
- Operating System: MacOS
- Browser: Chrome
- Paperize Version: ver.A7.0.1

**Additional context**
After reloading the page or signing in and out, the image will show up (even if there was no indication that the image was applied), and can be used from that moment with no problem.

**Comment by lorennorman** [comment]
Closing because #13 will supersede this problem by disallowing this use case (direct Drive usage) altogether.
