### ISSUE TITLE
PDF rendering broken in Firefox (maybe others?)

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#60]
**Describe the bug**
I don't see a PDF preview or get an error when I use Firefox.

**To Reproduce**
1. View an otherwise-working game compoent in Firefox.

**Expected behavior**
Should render.

**Additional context**
I think we should investigate a couple of libraries: PDFObject and PDF.js

PDFObject magically "does the right thing" for embedding a PDF in various browsers (some want a `embed` tag, some want an `object` tag, etc). May simple fix the problem, not sure:
https://pdfobject.com/

PDF.js is a Mozilla project for rendering a PDF via pure Javascript. This may fundamentally fix and standardize all PDF rendering across all browsers, forever. Or it may be a horrible jerk to work with, I do not know.
https://github.com/mozilla/pdf.js

These libraries handle different concerns and are made to work together.

The wrinkle for us with both of these is that we are creating the PDF live in the page, so the embed instructions usually aren't exactly right.

**Comment by shawn-mcgee** [comment]
Would it be possible to just use something like an <iframe> to embed the pdf? Just cache the render and point the iframe to it?

**Comment by lorennorman** [comment]
Possibly yes. Ply with it and see!

There are 3 different ways of rendering it in the pdf vue component. Different things have worked at different times, like FF definitely used to work.

But that’s the point, PDFObject should make this ongoing issue go away.

**Comment by riverole** [comment]
What does it exactly not work? What error do you see? I have a super simple template and it is rendering in Firefox fine. Is it the images? Also, is this different from #41 ? I know it says private browsing there in that one, but inside the issue itself you say that it was happening also without private browsing?

**Comment by lorennorman** [comment]
Dang, mine's just not rendering anything between the pagination:
<img width="468" alt="Screen Shot 2020-06-04 at 10 33 47 PM" src="https://user-images.githubusercontent.com/17697/83830621-9527ed00-a6b3-11ea-87a6-7ec2fb843eaa.png">

...but I'm also not getting any console errors.

Thanks for letting me know, I'll have to poke some more with different templates and see if i can narrow this down.

**Comment by lorennorman** [comment]
This stopped happening for me in a recent Firefox update, closing!
