### ISSUE TITLE
Better visualize Drive asset creation on Game create

### ISSUE THREAD

**Issue by riverole** [paperize/paperize#66]
Let's strengthen our convictions about how Paperize interacts with Google Drive!

Reduce the 3 checkboxes to just one: "Create Drive assets?", and maybe a tooltip that explains exactly what gets created.

Upon clicking "create", we should show what work is happening (instead of jumping straight to the empty game and having the assets appear a moment later.)

1. User clicks "Create" with a valid game form.
2. App says "Creating Game Folder..."
3. App says "Creating Game Images Subfolder..."
4. App says "Creating Game Components Sheet..."
5. App says "Done!" for a brief moment before
6. App forwards to the game screen

**Comment by riverole** [comment]
@lorennorman I have created this from a card in Project for Release 8, because I thought this might be a standalone issue that I could work on? Could you provide more details about it?

**Comment by lorennorman** [comment]
I'm second guessing this one.

**Comment by riverole** [comment]
Should we even allow not to create it through Paperize, with the new permissions paradigm? In which case someone would uncheck this and still able to use Paperize?

**Comment by lorennorman** [comment]
Answering for posterity:

Yeah you are right, let’s just make it automatic now that users shouldn’t
manually manage their Drives anymore. Instead of a checkbox we’ll do an
informational blurb so users know what’s happening.
