### ISSUE TITLE
Being able to combine multiple components into the same page

### ISSUE THREAD

**Issue by riverole** [paperize/paperize#8]
**Is your feature request related to a problem? Please describe.**
Sometimes there's components that have very little amount of cards, so they end up being a bit of a waste of paper.

**Describe the solution you'd like**
It would be great if you could have the ability to print by combining different components, so if component A has 10 cards, and component B has 8 cards, they can be printed in 2 papers instead of 3.

**Describe alternatives you've considered**
The existing alternative is printing each component in a new page. However, we could keep both and just allow them as a toggle.

**Additional context**
See the issue:
<img width="402" alt="unoptimalUtilizationOfPaper" src="https://user-images.githubusercontent.com/4833422/73116562-29579b80-3eed-11ea-89f0-64ccfbfd51bc.png">

**Comment by lorennorman** [comment]
Great awareness, this is a good feature. Some things that I've learned over the years:

**It must be a setting**
Some users want this, some users do not want this, and it has existed both ways.

**Same-Size Components Are Easy**
If it's all cards, then there's not much to think about, we can interleave components quite easily. When they're differently sized, however...

**Packing is Hard**
Two-dimensional packing is an open problem, there isn't a known way to get the "best" packing performance (in this case minimizing paper waste), and it complicates the layout code immensely.

Exposing it as a print setting and only allowing it on same-size components is a no-brainer to me, and probably helps 90% of people who care about this!

**Comment by riverole** [comment]
Will do the same size grouping then as part of this issue, as a setting. Different sizes seems too complicated for what it is worth.
